nguage: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
# command to install dependencies
install: 
  - "sudo pip install -r development.deps"
  - "sudo apt-get install python-all fakeroot"
# command to run tests
script:
  - python setup.py clean
  - python setup.py build
  - python setup.py test
  - python setup.py sdist
  - python setup.py bdist
  - python setup.py bdist_egg
#  - python setup.py --command-packages=stdeb.command sdist_dsc bdist_deb
  
